---
booktitle: Proceedings of the 25th Annual Conference on Learning Theory
publisher: JMLR Workshop and Conference Proceedings
month: 0
volume: 23
year: '2012'
start: 2012-06-25
end: 2012-06-27
published: 2012-06-16
shortname: COLT 2012
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: MannorCOLT2012
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
editor:
- given: Shie
  family: Mannor
- given: Nathan
  family: Srebro
- given: Robert C.
  family: Williamson
description: |
  Proceedings of the 25th Annual Conference on Learning Theory
    Held in Edinburgh, Scotland on 25-27 June 2012

  Published as Volume 23 by the Proceedings of Machine Learning Research on 16 June 2012.

  Volume Edited by:
    Shie Mannor
    Nathan Srebro
    Robert C. Williamson

  Series Editors:
    Neil D. Lawrence
date_str: 25--27 Jun
url: http://proceedings.mlr.press
baseurl: "/v23"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v23
bibtex_copy: true
email: ''
conference:
  name: Conference on Learning Theory
  url: 
  location: Edinburgh, Scotland
  dates:
  - 2012-06-25
  - 2012-06-26
  - 2012-06-27
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v23.bib
