---
booktitle: Proceedings of the 25th Annual Conference on Learning Theory
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
publisher: JMLR Workshop and Conference Proceedings
month: 0
volume: 23
year: '2012'
start: 2012-06-25
end: 2012-06-27
published: 2012-06-16
shortname: COLT 2012
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: MannorCOLT2012
cycles: false
editor:
- given: Shie
  family: Mannor
- given: Nathan
  family: Srebro
- given: Robert C.
  family: Williamson
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 25th Annual Conference on Learning Theory
    Held in Edinburgh, Scotland on 25-27 June 2012

  Published as Volume 23 by the Proceedings of Machine Learning Research on 16 June 2012.

  Volume Edited by:
    Shie Mannor
    Nathan Srebro
    Robert C. Williamson

  Series Editors:
    Neil D. Lawrence
date_str: 25--27 Jun
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v23"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v23
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Conference on Learning Theory
  url: 
  location: Edinburgh, Scotland
  dates:
  - 2012-06-25
  - 2012-06-26
  - 2012-06-27
  number: 25
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
